CREATE DATABASE crudnodejs;

USE crudnodejs;

CREATE TABLE student (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(100) NOT NULL,
  phone VARCHAR(15)
);


SELECT * FROM student;